### ISSUE TITLE
Problems training the model

### ISSUE THREAD

**Issue by MasterLucas** [materialsintelligence/mat2vec#28]
Dear community, 

I'm having a problem running the line code to train the model on the corpus example. The following error messages are printed.

<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2022-06-10 00:06:51,569 : INFO : Basic min_count trim rule for formula.
2022-06-10 00:06:51,569 : INFO : Not including extra phrases, option not specified.
Traceback (most recent call last):
  File "/home/lucas_bandeira/Documents/mat2vec/mat2vec/training/phrase2vec.py", line 165, in <module>
    sentences, phraser = wordgrams(processed_sentences,
  File "/home/lucas_bandeira/Documents/mat2vec/mat2vec/training/phrase2vec.py", line 44, in wordgrams
    phrases = Phrases(
TypeError: \_\_init\_\_() got an unexpected keyword argument 'common_terms'

Could somebody help me to solve this problem?

Sincerely yours,

**Comment by jdagdelen** [comment]
This is most likely a package version issue. Can you double check you followed the installation setup instructions?

**Comment by MasterLucas** [comment]
I just checked the packages installed and all of them satisfy the requirements. The python version I am using is 3.6.13. Might this be the problem?
